Django_heavens/urls.py
from django.contrib import admin
from django.urls import path, include
from autenticacion import views as principal

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include('autenticacion.urls')),
    path('nomina/', include('nomina.urls')),
    path('operaciones/', include('operaciones.urls')),
    path('', principal.home, name='home_principal')
]

nomina/urls.py
from django.urls import path
from . import views
from .views import JornadaListView


urlpatterns = [
    path("", views.nomina_home, name="nomina_home"),
    path('registrohoras', views.registrohoras, name='registrohoras'), 
    path('home_nomina', views.home_nomina, name='home_nomina'),
    path('jornadas/', views.jornadas, name='jornadas'),
    path('jornadas/lista/', views.list_jornadas, name='lista_jornadas'),
    path('jornadas/crear/', views.crear_jornada, name='crear_jornada'),
    path('jornadas/actualizar/<int:jornada_id>/', views.actualizar_jornada, name='actualizar_jornada'),
    path('jornadas/eliminar/<int:jornada_id>/', views.eliminar_jornada, name='eliminar_jornada'),
    path('jornadas/importar/', views.importar_excel_jor, name='import_jornada'),
    path('jornadas/exportar/', views.export_jor_excel, name='export_jornada'),
    path('empleados/', views.empleados, name='empleados'),
    path('empleados/lista/', views.list_empleados, name='lista_empleados'),
    path('empleados/crear/', views.crear_empleado, name='crear_empleado'),
    path('empleados/actualizar/<int:empleado_id>/', views.actualizar_empleado, name='actualizar_empleado'),
    path('festivos/crear/', views.crear_festivo, name='crear_festivo'),
    path('festivos/exportar/', views.export_festivos_excel, name='export_festivos'),
    path('festivos/importar/', views.importar_excel_festivos, name='importar_festivos'),
    path('empleados/importar/', views.importar_excel_emp, name='import_empleado'),
    path('empleados/exportar/', views.export_emp_excel, name='export_empleado'),
    path('cargos/importar/', views.importar_excel_cargo, name='import_cargo'),
    path('cargos/exportar/', views.export_cargos_excel, name='export_cargo'),
    path('cargos/crear/', views.crear_cargo, name='crear_cargo'),
    path('operaciones/', views.ope_home, name='ope_home'),
    path('operaciones/jornadas/', views.ope_jornadas, name='ope_jornadas'),
    path('operaciones/jornadas/lista/', views.ope_list_jornadas, name='ope_lista_jornadas'),
    path('operaciones/jornadas/crear/', views.ope_crear_jornada, name='ope_crear_jornada'),
    path('operaciones/jornadas/actualizar/<int:jornada_id>/', views.ope_actualizar_jornada, name='ope_actualizar_jornada'),
    path('operaciones/jornadas/eliminar/<int:jornada_id>/', views.ope_eliminar_jornada, name='ope_eliminar_jornada'),
    path('operaciones/jornadas/importar/', views.ope_importar_excel_jor, name='ope_import_jornada'),
    path('operaciones/jornadas/exportar/', views.ope_export_jor_excel, name='ope_export_jornada'),
    path('operaciones/empleados/', views.ope_empleados, name='ope_empleados'),
    path('operaciones/empleados/lista/', views.ope_list_empleados, name='ope_lista_empleados'),
    path('operaciones/festivos/ver/', views.ope_crear_festivo, name='ope_crear_festivo'),
    path('operaciones/cargos/ver/', views.ope_crear_cargo, name='ope_crear_cargo'),
    path('prueba', JornadaListView.as_view(), name='prueba'),
]

operaciones/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home_inventario_tr', views.inventariotr, name='homeinventariotr'),
    path('intentariotr_items_list', views.InventarioRealListView.as_view(), name='inventariotrlist'),
    path('intentariotr_items_mover', views.InventarioCreateView.as_view(), name='inventariotrmover'),
    path('historico_items', views.MovimientoListView.as_view(), name='historicos'),
    path('recibo_items_list', views.ItemListView.as_view(), name='reciboitemslist'),
    path('recibo_items_create', views.ItemCreateView.as_view(), name='reciboitemscreate'),
    path('historico_muestreo_items', views.MuestreoHistoricoListView.as_view(), name='historicos_muestreo'),
    path('muestreo_items_list', views.MuestreoListView.as_view(), name='muestreoitemslist'),
    path('muestreo_items_create', views.MuestreoCreateView.as_view(), name='muestreoitemscreate'),
    path('home_muestreo', views.muestreo, name='homemuestreo')
]

operaciones/forms.py
from django import forms
from .models import Item, Bodega, Defectos


class InventarioRealForm(forms.Form):
    bodegas_excluidas = ["Nacional", "Devolucion", "Exportacion", "Perdida"]
    item = forms.ModelChoiceField(queryset=Item.objects.exclude(bodega__nombre__in=bodegas_excluidas))
    cantidad = forms.DecimalField()
    bodegas_excluidas2 = ["Nacional", "Devolucion", "Exportacion", "Perdida", "Recibo"]
    bodega_destino = forms.ModelChoiceField(queryset=Bodega.objects.exclude(nombre__in=bodegas_excluidas2),
                                            required=True)

    def __init__(self, *args, **kwargs):
        kwargs.pop('instance', None)
        super().__init__(*args, **kwargs)
        if 'item' in self.initial:
            item = self.initial['item']
            self.fields['cantidad'].initial = item.kilos_netos
            self.fields['item'].queryset = self.fields['item'].queryset.filter(pk=item.pk)

    """def clean(self):
        cleaned_data = super().clean()
        item = cleaned_data.get('item')
        cantidad = cleaned_data.get('cantidad')
        bodega_destino = cleaned_data.get('bodega_destino')

        if item and cantidad:
            if cantidad > item.kilos_netos:
                self.add_error('cantidad',
                               f"Debes mover menos de ({item.kilos_netos}) kilos netos para el item {item}.")

            if cantidad < 0:
                self.add_error('cantidad', "La cantidad de kilos a mover debe ser un número mayor a 0.")

            if cantidad == item.kilos_netos and not bodega_destino:
                self.add_error('bodega_destino', "Debes seleccionar una bodega de destino para dar salida al item.")

        return cleaned_data"""


class ItemForm(forms.ModelForm):
    """defectos = forms.MultipleChoiceField(
        choices=[(defecto.nombre_defectos, defecto.nombre_defectos) for defecto in Defectos.objects.all()],
        widget=forms.CheckboxSelectMultiple,
        required=False
    )"""

    class Meta:
        model = Item
        fields = ['numero_item', 'kilos_netos', 'fruta', 'bodega', 'tipo_negociacion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        bodega_predeterminada = Bodega.objects.get(nombre='Recibo')
        self.fields['bodega'].initial = bodega_predeterminada
        self.fields['bodega'].disabled = True
        self.fields['numero_item'].widget.attrs.update({'oninput': 'this.value = this.value.toUpperCase()'})

    def clean_numero_item(self):
        numero_item = self.cleaned_data.get('numero_item')
        if numero_item:
            numero_item = "R" + numero_item.upper()
        return numero_item

    """if self.instance and self.instance.defectos:
            self.fields['defectos'].initial = self.instance.defectos.split(',')

    def clean_defectos(self):
        defectos = self.cleaned_data.get('defectos')
        if defectos:
            return ','.join(defectos)
        return defectos"""


# Boton (Buscar Item, todos los modulos.)
class SearchForm(forms.Form):
    item_busqueda = forms.CharField(max_length=256, required=False)


# Formulario De Muestreo Porcentajes
class MuestreoForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['numero_item', 'porcen_muestreo', 'tipo_muestreo', 'lider_muestreo', 'emp_muestreo']

    def __init__(self, *args, **kwargs):
        super(MuestreoForm, self).__init__(*args, **kwargs)
        self.fields['numero_item'].widget.attrs['readonly'] = True

operaciones/views.py
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView
from django_tables2 import SingleTableView
from .forms import InventarioRealForm, ItemForm, SearchForm, MuestreoForm
from .models import Bodega, Item, Movimiento, Movimientosmuestreo
from .tables import MovimientoTable, ItemTable, InventariorealTable, MuestreoTable, MovimientoMuestreoTable


@login_required
@permission_required('operaciones.view_movimiento', raise_exception=True)
def inventariotr(request):
    return render(request, 'home_inventariotr.html')


def muestreo(request):
    return render(request, 'home_muestreo.html')


# --------------------////-----------Movimientos. (Inventario Real Aux Admin)-----------------------//:

class InventarioRealListView(SingleTableView):
    model = Item
    table_class = InventariorealTable
    template_name = 'inventariotr_list_item.html'
    form_class = SearchForm

    def get_queryset(self):
        bodegas_excluidas = ["Devolucion", "Nacional", "Exportacion", "Perdida", "Calidad"]
        queryset = self.model.objects.exclude(bodega__nombre__in=bodegas_excluidas)
        form = self.form_class(self.request.GET)
        if form.is_valid() and form.cleaned_data.get('item_busqueda'):
            item_busqueda = form.cleaned_data.get('item_busqueda')
            queryset = queryset.filter(numero_item__icontains=item_busqueda)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_busqueda'] = self.form_class(self.request.GET)
        return context


# ---------- Formulario Para Inventario en Tiempo Real -----------------------------------
class InventarioCreateView(CreateView):
    model = Item
    form_class = InventarioRealForm
    template_name = 'inventariotr_mover_item.html'
    success_url = '/intentariotr_items_list/'

    def get(self, request, *args, **kwargs):
        item_id = request.GET.get('item_id', None)
        if item_id:
            item = Item.objects.get(pk=item_id)
            form = self.form_class(initial={'item': item})
            return render(request, self.template_name, {'form': form})
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        usuario = self.request.user
        item = form.cleaned_data['item']
        cantidad = form.cleaned_data['cantidad']
        bodega_destino = form.cleaned_data['bodega_destino']
        if cantidad > 0:
            if cantidad <= item.kilos_netos and item.bodega != bodega_destino:
                try:
                    # Buscar el mismo Item y combinar los kilos en la misma bodega.
                    existing_item = Item.objects.get(numero_item=item.numero_item, bodega=bodega_destino)
                    existing_item.kilos_netos += cantidad
                    existing_item.save()
                except Item.DoesNotExist:
                    Item.objects.create(numero_item=item.numero_item, kilos_netos=cantidad,
                                        bodega=bodega_destino, fruta=item.fruta,
                                        tipo_negociacion=item.tipo_negociacion, user=usuario)
                item.kilos_netos -= cantidad
                item.save()
                movimiento = Movimiento(item_historico=item.numero_item, cantidad=cantidad,
                                        bodega_origen=item.bodega,
                                        bodega_destino=bodega_destino, fruta=item.fruta,
                                        t_negociacion=item.tipo_negociacion, user=usuario)
                movimiento.save()
                messages.success(self.request, f'El item se movido exitosamente a la bodega {bodega_destino}.')
                if item.kilos_netos == 0:
                    item.delete()
                return JsonResponse({'success': True})

            elif item.bodega == bodega_destino:
                error_msg = f"La bodega de origen -> {item.bodega}, es igual a la bodega destino -> {bodega_destino}"
                return JsonResponse({'success': False, 'error': error_msg})
            else:
                error_msg = f"No hay suficiente stock disponible para dar salida a {cantidad} kilos netos. Kilos Netos disponibles: {item.kilos_netos}"
                return JsonResponse({'success': False, 'error': error_msg})
        else:
            error_msg = "La cantidad de kilos netos debe ser mayor que 0."
            return JsonResponse({'success': False, 'error': error_msg})

    def form_invalid(self, form):
        return JsonResponse({'success': False, 'html': render_to_string(self.template_name, {'form': form})})


# -----------------------------------------////----------------------------------//


# Tabla De Historico De Movimientos. (Inventario Real)
class MovimientoListView(SingleTableView):
    model = Movimiento
    table_class = MovimientoTable
    template_name = 'historico.html'
    form_class = SearchForm

    def get_queryset(self):
        queryset = super().get_queryset()
        form = self.form_class(self.request.GET)
        if form.is_valid():
            item_busqueda = form.cleaned_data.get('item_busqueda')
            if item_busqueda:
                queryset = queryset.filter(item_historico__icontains=item_busqueda)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_busqueda'] = self.form_class(self.request.GET)
        return context


# Mostrar Tabla Recibo - Bodega Recibo (Inventario Real)
class ItemListView(SingleTableView):
    model = Item
    table_class = ItemTable
    template_name = 'recibo_items_list.html'
    form_class = SearchForm

    def get_queryset(self):
        bodega_especifica = Bodega.objects.get(nombre='Recibo')
        queryset = super().get_queryset().filter(bodega=bodega_especifica)
        form = self.form_class(self.request.GET)
        if form.is_valid() and form.cleaned_data.get('item_busqueda'):
            item_busqueda = form.cleaned_data.get('item_busqueda')
            queryset = queryset.filter(numero_item__icontains=item_busqueda)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_busqueda'] = self.form_class(self.request.GET)
        return context


# -------------------------------  Formulario - Crear Item - Modal (Inventario Real) ----------------------------
class ItemCreateView(CreateView):
    model = Item
    form_class = ItemForm
    template_name = 'recibo_crear_item.html'
    success_url = '/recibo_items/'

    def get_initial(self):
        initial = super().get_initial()
        bodega_predeterminada = Bodega.objects.get(nombre='Recibo')
        initial['bodega'] = bodega_predeterminada
        return initial

    def form_valid(self, form):
        numero_item = form.cleaned_data['numero_item']
        fruta = form.cleaned_data['fruta']
        bodega = form.cleaned_data['bodega']
        kilos_netos = form.cleaned_data['kilos_netos']

        if Item.objects.filter(numero_item=numero_item).exclude(fruta=fruta).exists():
            error_msg = f'Ya existe este Item {numero_item}, con fruta diferente, revise la fruta que esta ingresando: {fruta}.'
            return JsonResponse({'success': False, 'error': error_msg})

        # Buscar el item igual en la misma bodega con el mismo numero_item y fruta
        try:
            existing_item = Item.objects.get(numero_item=numero_item, fruta=fruta, bodega=bodega)
            existing_item.kilos_netos += kilos_netos  # Sumar los kilos_netos
            existing_item.save()
            Movimiento.objects.create(
                item_historico=existing_item.numero_item,
                cantidad=existing_item.kilos_netos,
                bodega_origen=existing_item.bodega,
                bodega_destino=existing_item.bodega,
                fruta=existing_item.fruta.nombre_fruta,
                t_negociacion=existing_item.tipo_negociacion,
                fecha=timezone.now(),
                user=existing_item.user
            )
            return JsonResponse({'success': True})
        except Item.DoesNotExist:
            pass

        form.instance.user = self.request.user
        item = form.save()
        Movimiento.objects.create(
            item_historico=item.numero_item,
            cantidad=item.kilos_netos,
            bodega_origen=item.bodega,
            bodega_destino=item.bodega,
            fruta=item.fruta.nombre_fruta,
            t_negociacion=item.tipo_negociacion,
            fecha=timezone.now(),
            user=item.user
        )
        messages.success(self.request, f'El item {numero_item} se ha creado exitosamente.')
        return JsonResponse({'success': True})

    def form_invalid(self, form):
        return JsonResponse({'success': False, 'html': render_to_string(self.template_name, {'form': form})})


# ////////------------------------------------- Porcentaje De Muestreo -------------------------////////

class MuestreoListView(SingleTableView):
    model = Item
    table_class = MuestreoTable
    template_name = 'muestreo_list_item.html'
    form_class = SearchForm

    def get_queryset(self):
        bodegas_excluidas = ["Devolucion", "Nacional", "Exportacion", "Perdida", "Calidad"]
        queryset = self.model.objects.exclude(bodega__nombre__in=bodegas_excluidas)
        form = self.form_class(self.request.GET)
        if form.is_valid() and form.cleaned_data.get('item_busqueda'):
            item_busqueda = form.cleaned_data.get('item_busqueda')
            queryset = queryset.filter(numero_item__icontains=item_busqueda)
        return queryset

operaciones/templates/crear_item.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventario Frutas Tiempo Real</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/crear_item.css' %}"/>

</head>
<body>
<div class="modal-header">
    <h5 class="modal-title">Crear Item</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form action="{% url 'item_create' %}" method="post">
    {% csrf_token %}
    <div class="modal-body">
        <div id="errores">
            {% for field, error_list in form.errors.items %}
                {% for error in error_list %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endfor %}
        </div>
        {{ form.as_p }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
</body>
</html>

operaciones/templates/crear_item_button.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalCreateItem" href="{% url 'item_create' %}">Crear Item</button>
</body>
</html>

operaciones/templates/historico_muestreo.html
{% extends 'opbase.html' %} {% block content %}
        {% load static %}
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Historico Muestreo</title>
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
                        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
                        crossorigin="anonymous">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
                <link rel="stylesheet" href="{% static 'css/historico.css' %}"/>
        </head>
        <body>
        <br>
        <h1 class="align-center">Historico De Porcentajes De Muestreo</h1>
        <br>
        {% load django_tables2 %}
        <form method="get">
                <div class="d-flex">
        {{ item_busqueda }}
        <div class="d-grid gap-2 d-md-flex justify-content-between">
        <button class="btn btn-secondary" type="submit"><i class="bi bi-search"></i></button>
                <a type="button" class="btn btn-danger me-md-5 btn-lg" name="volver" role="button" href="{% url 'homemuestreo' %}"><i class="bi bi-arrow-return-left"></i></a>
        </div>
        </div>
        </form>
        {% render_table table %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
                integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
                integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
                crossorigin="anonymous"></script>
        </body>
        </html>
{% endblock %}

operaciones/templates/inventariotr_mover_button.html
<button type="button" class="btn btn-primary mover-button" id="mover" data-item-id="{{ record.pk }}">
    Mover
</button>

operaciones/templates/mover_button.html
<button type="button" class="btn btn-primary mover-button" data-item-id="{{ record.pk }}">
    Mover
</button>

operaciones/templates/mover_item.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inventario Frutas Tiempo Real</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/mover_item.css' %}"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    </head>
<body>
    <br>
    <h1>Items en bodega</h1>
    <br><br><br>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a type="button" class="btn btn-danger me-md-5 btn-lg" role="button" href="{% url 'homeinventariotr' %}"><i class="bi bi-arrow-return-left"></i></a>
    </div>
    <div class="container">
    {% load django_tables2 %}
    {% render_table table %}
    </div>
    <!-- Mover Item Modal -->
    <div class="modal fade text-white" id="moverItemModal" tabindex="-1" role="dialog" aria-labelledby="moverItemModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content bg-dark">
                <div class="modal-header">
                    <h5 class="modal-title" id="moverItemModalLabel">Mover Item</h5>
                </div>
                <form id="moverItemForm" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div id="errores">
                            {% for field, error_list in form.errors.items %}
                                {% for error in error_list %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            {% endfor %}
                        </div>
                        {{ form.as_p }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Mover Item</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
    // Evento de clic para abrir el modal
    $('.mover-button').click(function () {
        var itemId = $(this).data('item-id');
        $('#id_item').val(itemId).prop('disabled', true);
        $('#moverItemModal').modal('show');
    });
    $('#moverItemForm').on('submit', function (event) {
        event.preventDefault();
        $('#id_item').prop('disabled', false);
        $.ajax({
            url: '/operaciones/items/mover/',
            type: 'post',
            data: $(this).serialize(),
            success: function (data) {
                if (data.success) {
                    $('#moverItemModal').modal('hide');
                    location.reload();
                } else {
                    console.log(data);
                    var errorMessage = data.error;
                    $('#errores').html('<div class="alert alert-danger">' + errorMessage + '</div>');
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log("AJAX Error: ", textStatus, errorThrown);
            }
        });
    });
});

</script>
</body>
</html>

operaciones/templates/muestreo_muestra_button.html
<button type="button" class="btn btn-primary mover-button" id="muestrear" data-item-id="{{ record.pk }}">
    Muestrear
</button>

operaciones/templates/recibo_crear_item_button.html
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalCreateItem" href="{% url 'recibo_items_create' %}">Crear Item</button>
</body>
</html>